name: code-coverage
on:
  workflow_dispatch:
  #pull_request:
  #types: [opened, edited, synchronize, reopened]
  #paths:
  #- "force-app/**"
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install @salesforce/cli --global
      - name: Populate auth file
        run: 'echo "${{ secrets.SALESFORCE_AUTH_URL }}" > ./SALESFORCE_AUTH_URL.txt'
      - name: Authenticate Dev Hub
        run: 'sf org login sfdx-url --sfdx-url-file ./SALESFORCE_AUTH_URL.txt --alias DevHub --set-default-dev-hub'
      - name: Create Scratch Org
        run: sf force org create scratch --setdefaultusername --definitionfile config/project-scratch-def.json --setalias ciorg --durationdays 1
      - name: Deploy source
        run: sf force source push
      - name: Run Apex tests
        run: sf apex run test --code-coverage --result-format human --output-dir ./
      - name: Delete coverage file (temporary fix)
        run: rm ./test-result-707*-codecoverage.json
      - name: 'Upload code coverage for Apex to Codecov.io'
        uses: codecov/codecov-action@v3
        with:
          flags: Apex
      - name: Delete Scratch Org
        run: sf force org delete scratch --no-prompt
